column_width = 120 # set the column width to 120
line_endings = "Unix" # set the line endings to Unix
indent_type = "Spaces" # set the indent type to spaces
indent_width = 2 # set the indent width to 2
quote_style = "AutoPreferDouble" # set the quote style to AutoPreferDouble
call_parentheses = "None" # set the call parentheses to None