# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
palette = "catppuccin_macchiato"

add_newline = true
command_timeout = 1000
scan_timeout = 10
format = '''
[┌](surface1) $os$memory_usage$battery$sudo$username$directory$git_branch$git_commit$git_metrics$kubernetes $fill $container$meson$direnv$helm$dart$deno$nodejs$golang$rust$package
[└─$cmd_duration$character](surface1) '''

# set up the character module to display the prompt character
[character]
success_symbol = "[❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = "[❮](purple)"
vimcmd_replace_symbol = "[❮](purple)"
vimcmd_visual_symbol = "[❮](yellow)"

# Set the OS model to display the OS icon
[os]
format = '[$symbol]($style)'
style = "bold text"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# Set username module to display the current user's username
[username]
style_user = 'blue bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[sudo]
format = '[as $symbol]($style)'
symbol = '🧙 '
allow_windows = true
disabled = true

# Set up the battery module to display the battery percentage
[battery]
format = '[$symbol$percentage]($style) '
full_symbol = " "
charging_symbol = ""
discharging_symbol = "󰂃"
unknown_symbol = " "
empty_symbol = " "
disabled = false

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

# Set up cmd_duration module to display the time it took for the last command to execute
[cmd_duration]
format = ' 󰔚 [$duration](bold yellow) '

# Shows current directory
[directory]
format = 'at [$path]($style)[$read_only]($read_only_style) '
truncation_length = 3
truncation_symbol = '…/'
home_symbol = ' ~'
read_only_style = 'red'
read_only = '  '

[dart]
symbol = " "

[deno]
format = '[$symbol($version )]($style) '
symbol = "🦕"

[docker_context]
format = '[$symbol$context]($style) '
symbol = "🐳 "

[git_branch]
always_show_remote = false
format = 'on [$symbol$branch(:$remote_branch)]($style) '
symbol = " "
style = ' sky'

[git_commit]
commit_hash_length = 3
format = '[\($hash$tag\)]($style)'
style = 'yellow'
only_detached = true
tag_disabled = true
tag_max_candidates = 0
tag_symbol = "🏷️ "

[git_metrics]
format = '([$added]($added_style))([$deleted]($deleted_style)) '
disabled = false
only_nonzero_diffs = false

[golang]
format = '[$symbol($version )]($style) '
symbol = ""
style = 'bold blue'

[helm]
format = '[$symbol($version )]($style) '
style = 'bold blue'

[kubernetes]
format = '⋯ [$symbol ( $user on )$context\($namespace\)]($style) '
style = 'bold sky'
symbol = "⛵"
disabled = false
contexts = [
    { context_pattern = "minikube", symbol = "🐳⛵" },
]

[lua]
format = '[$symbol($version )]($style) '
symbol = ""
style = 'bold blue'

[memory_usage]
format = '[$symbol${ram}( | ${swap})]($style) '
disabled = false
threshold = 95
symbol = '󰍛'
style = 'pink'

[meson]
format = '[$symbol$project]($style) '

[nodejs]
format = '[$symbol($version)]($style) '
style = 'bold green'

[package]
style = 'bold peach'
symbol = "📦 "

[rust]
format = '[$symbol($version )]($style) '
symbol = ""
style = 'bold red'

[terraform]
format = '[$symbol$workspace]($style) '
symbol = "󱁢"
style = 'bold mauve'

# palette tables should be last in the config ⚓️
# Catppucci theme
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
