
[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Home 🏡"
path = "~"
startup_command = "l"

[[session]]
name = "Code 💻"
path = "~/Projects"
startup_command = "l"

[[session]]
name = "GitHub 💻"
path = "~/Projects/GitHub/"
startup_command = "l"

[[session]]
name = "Clients 💻"
path = "~/Projects/Clients"
startup_command = "l"

[[session]]
name = "tmux config 🪟"
path = "~/dotfiles/tmux"
startup_command = "nvim .config/tmux/tmux.conf"

[[session]]
name = "wezterm config 🌌"
path = "~/dotfiles/wezterm"
startup_command = "nvim .config/wezterm/wezterm.lua"

[[session]]
name = "sesh config 🌌"
path = "~/dotfiles/tmux/"
startup_command = "nvim .config/sesh/sesh.toml"

[[session]]
name = "dotfiles 🔧"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"
