[manager]
ratio = [1, 2, 4]
sort_by = "modified"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 2000
max_height = 1200
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[asks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false